# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-17 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='none as of now'),
            preserve_default=False,
        ),
    ]
